spring:
  application:
  name: fashion-shop

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:fashion_shop}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

server:
  port: ${PORT:5454}

jwt:
  secret: Qqt/ie/wY52lPujgC5CN5GY+5rhplntrVRAGxge01rEC7OIv9jhqbhbmSi2pWpnoxhzRibH3At9ZOtnXyIsHnvexOTq6CKPDZbfyP3HVFMc=

ngrok-url: https://4a73-116-111-185-194.ngrok-free.app
vnpay:
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: ${VNPAY_RETURN_URL:http://localhost:5454/api/payment/vnpay-callback}
  tmn-code: "2FVUEZLT"
  secret-key: "Y4UO6Z9XMLH7II6RJXBXG6MYBKPH12Z6"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"