spring:
  application:
  name: fashion-shop

  datasource:
    url: jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:fashion_shop}
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: ${REDISHOST:localhost}
    port: ${REDISPORT:6379}
    password: ${REDISPASSWORD:}

server:
  port: ${PORT:5454}

jwt:
  secret: Qqt/ie/wY52lPujgC5CN5GY+5rhplntrVRAGxge01rEC7OIv9jhqbhbmSi2pWpnoxhzRibH3At9ZOtnXyIsHnvexOTq6CKPDZbfyP3HVFMc=

ngrok-url: https://4a73-116-111-185-194.ngrok-free.app
vnpay:
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: ${VNPAY_RETURN_URL:http://localhost:5454/api/payment/vnpay-callback}
  tmn-code: "2FVUEZLT"
  secret-key: "Y4UO6Z9XMLH7II6RJXBXG6MYBKPH12Z6"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"