export const FIND_PRODUCT_BY_ID_REQUEST = 'FIND_PRODUCT_BY_ID_REQUEST';
export const FIND_PRODUCT_BY_ID_SUCCESS = 'FIND_PRODUCT_BY_ID_SUCCESS';
export const FIND_PRODUCT_BY_ID_FAILURE = 'FIND_PRODUCT_BY_ID_FAILURE';

export const FIND_PRODUCTS_REQUEST = 'FIND_PRODUCT_BY_CATEGORY_REQUEST';
export const FIND_PRODUCTS_SUCCESS = 'FIND_PRODUCT_BY_CATEGORY_SUCCESS';
export const FIND_PRODUCTS_FAILURE = 'FIND_PRODUCT_BY_CATEGORY_FAILURE';

export const SET_PRODUCTS_BY_CATEGORY = 'SET_PRODUCTS_BY_CATEGORY';

// Search suggestions actions
export const SEARCH_SUGGESTIONS_REQUEST = 'SEARCH_SUGGESTIONS_REQUEST';
export const SEARCH_SUGGESTIONS_SUCCESS = 'SEARCH_SUGGESTIONS_SUCCESS';
export const SEARCH_SUGGESTIONS_FAILURE = 'SEARCH_SUGGESTIONS_FAILURE';
export const CLEAR_SEARCH_SUGGESTIONS = 'CLEAR_SEARCH_SUGGESTIONS';

// Search products actions
export const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE';